apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hcp-20-hosted-cluster
  namespace: openshift-gitops
  labels:
    cluster-type: hosted
    platform: kubevirt
    managed-by: gitops
spec:
  project: default
  source:
    repoURL: https://github.com/jithunarayanan/ztp-gitops.git
    targetRevision: main
    path: hosted-clusters/hcp-20
    # kustomize:
    #   namePrefix: prod-
    #   commonLabels:
    #     env: production
    # helm:
    #   valueFiles:
    #     - values-production.yaml
    #   parameters:
    #     - name: cluster.name
    #       value: hcp-02
  destination:
    server: https://kubernetes.default.svc
    namespace: clusters
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
